language: python
env:
  - TOXENV=py26
  - TOXENV=py27
  - TOXENV=py33
  - TOXENV=py34
  - TOXENV=pypy
install:
  - travis_retry pip install tox
  - pip install coveralls
  - pip install codecov
script:
  - tox
  - coverage run --source=iawscli tests/run_tests.py
after_success:
  - coveralls
  - codecov
