language: python
virtualenv:
  system_site_packages: true
env:
  - TOXENV=py26
  - TOXENV=py27
  - TOXENV=py33
  - TOXENV=py34
  - TOXENV=pypy
os:
  - linux
  - osx
install:
  - travis_retry pip install tox
  - pip install coveralls
  - pip install codecov
script:
  - tox
after_success:
  - coveralls
  - codecov
